forest:
  variables:
    url: https://discord.com/api/v10/
  # 连接池最大连接数（默认为 500）
  max-connections: 1000
  # 每个路由的最大连接数（默认为 500）
  max-route-connections: 500
  # 请求超时时间，单位为毫秒（默认为 3000）
  timeout: 60000
  # 连接超时时间，单位为毫秒（默认为 timeout）
  connect-timeout: 60000
  # 数据读取超时时间，单位为毫秒（默认为 timeout）
  read-timeout: 60000
  # 请求失败后重试次数（默认为 0 次不重试）
  max-retry-count: 5
  # 打开或关闭日志（默认为 true）
  logEnabled: true
  # 打开/关闭Forest请求日志（默认为 true）
  log-request: true
  # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-status: true
  # 打开/关闭Forest响应内容日志（默认为 false）
  log-response-content: true


